### ISSUE TITLE
QQ : https://github.com/squeek502/lua-aes / lua-hmac / lua-hashlib

### ISSUE THREAD

**Issue by nodecentral** [squeek502/ryanliptak.com#1]
Hi Ryan

Sorry to have to ask this via an Issue, but I had the following links for you, which seems to be broken now.. By any chance are they still available somewhere ?

https://github.com/squeek502/lua-aes
https://github.com/squeek502/lua-hmac
https://github.com/squeek502/lua-hashlib

**Comment by squeek502** [comment]
Those repositories have never existed, actually. Where did you happen to come across links to them?

**Comment by nodecentral** [comment]
Interesting, (thanks for responding) 

I was using ChatGPT (well the Playground area) and asked it to convert some Python code to Lua (to control a Panasonic TV), and to include links to any libraries/modules I’d need, and 3 of the 4 links it gave me were to you ? (I went back and asked it for alternative links and everything it’s given me so far has been a broken link, even thought it claims to have checked them..

**Comment by squeek502** [comment]
Very strange! Good luck getting it to stop hallucinating 😄

**Comment by nodecentral** [comment]
> Very strange! Good luck getting it to stop hallucinating 😄

It’s definitely on something !!

By any chance - you don’t know how to do those things  :-) ?
